config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :leagues
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/league.rb
class League < ApplicationRecord
    has_and_belongs_to_many :users, join_table: "memberships"
end

app/models/membership.rb
class Membership < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_and_belongs_to_many :leagues, join_table: "memberships"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_league, only: %i[ show edit update destroy ]

  # GET /leagues or /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1 or /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues or /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to league_url(@league), notice: "League was successfully created." }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1 or /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to league_url(@league), notice: "League was successfully updated." }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1 or /leagues/1.json
  def destroy
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url, notice: "League was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def league_params
      params.require(:league).permit(:name, :description, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PingPiper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leagues/_form.html.erb
<%= form_with(model: league) do |form| %>
  <% if league.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
        <% league.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/leagues/_league.html.erb
<div id="<%= dom_id league %>">
  <p>
    <strong>Name:</strong>
    <%= league.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= league.description %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= league.code %>
  </p>

</div>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render "form", league: @league %>

<br>

<div>
  <%= link_to "Show this league", @league %> |
  <%= link_to "Back to leagues", leagues_path %>
</div>

app/views/leagues/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Leagues</h1>

<div id="leagues">
  <% @leagues.each do |league| %>
    <%= render league %>
    <p>
      <%= link_to "Show this league", league %>
    </p>
  <% end %>
</div>

<%= link_to "New league", new_league_path %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render "form", league: @league %>

<br>

<div>
  <%= link_to "Back to leagues", leagues_path %>
</div>

app/views/leagues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @league %>

<div>
  <%= link_to "Edit this league", edit_league_path(@league) %> |
  <%= link_to "Back to leagues", leagues_path %>

  <%= button_to "Destroy this league", @league, method: :delete %>
</div>